# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20181016_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='User',
        ),
    ]
